[package]
description = "AI-powered development tasks using Claude"
edition     = "2021"
name        = "xtask_agentic"
publish     = false
version     = "0.0.0"

[dependencies]
anyhow     = { workspace = true }
bpaf       = { workspace = true, features = ["derive"] }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
xtask      = { path = '../', version = "0.0" }

# Pretty print specific dependencies
pgt_pretty_print = { workspace = true }
pgt_query        = { workspace = true }
