//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Generated file, do not edit by hand, see `xtask/codegen`"]
use crate::rule::SplinterRule;
::pgls_analyse::declare_rule! { # [doc = "# No Primary Key\n\nDetects if a table does not have a primary key. Tables without a primary key can be inefficient to interact with at scale.\n\n## SQL Query\n\n```sql\n(\nselect\n    'no_primary_key' as \"name!\",\n    'No Primary Key' as \"title!\",\n    'INFO' as \"level!\",\n    'EXTERNAL' as \"facing!\",\n    array['PERFORMANCE'] as \"categories!\",\n    'Detects if a table does not have a primary key. Tables without a primary key can be inefficient to interact with at scale.' as \"description!\",\n    format(\n        'Table \\`%s.%s\\` does not have a primary key',\n        pgns.nspname,\n        pgc.relname\n    ) as \"detail!\",\n    'https://supabase.com/docs/guides/database/database-linter?lint=0004_no_primary_key' as \"remediation!\",\n     jsonb_build_object(\n        'schema', pgns.nspname,\n        'name', pgc.relname,\n        'type', 'table'\n    ) as \"metadata!\",\n    format(\n        'no_primary_key_%s_%s',\n        pgns.nspname,\n        pgc.relname\n    ) as \"cache_key!\"\nfrom\n    pg_catalog.pg_class pgc\n    join pg_catalog.pg_namespace pgns\n        on pgns.oid = pgc.relnamespace\n    left join pg_catalog.pg_index pgi\n        on pgi.indrelid = pgc.oid\n    left join pg_catalog.pg_depend dep\n        on pgc.oid = dep.objid\n        and dep.deptype = 'e'\nwhere\n    pgc.relkind = 'r' -- regular tables\n    and pgns.nspname not in (\n        '_timescaledb_cache', '_timescaledb_catalog', '_timescaledb_config', '_timescaledb_internal', 'auth', 'cron', 'extensions', 'graphql', 'graphql_public', 'information_schema', 'net', 'pgmq', 'pgroonga', 'pgsodium', 'pgsodium_masks', 'pgtle', 'pgbouncer', 'pg_catalog', 'pgtle', 'realtime', 'repack', 'storage', 'supabase_functions', 'supabase_migrations', 'tiger', 'topology', 'vault'\n    )\n    and dep.objid is null -- exclude tables owned by extensions\ngroup by\n    pgc.oid,\n    pgns.nspname,\n    pgc.relname\nhaving\n    max(coalesce(pgi.indisprimary, false)::int) = 0)\n```\n\n## Configuration\n\nEnable or disable this rule in your configuration:\n\n```json\n{\n  \"splinter\": {\n    \"rules\": {\n      \"performance\": {\n        \"noPrimaryKey\": \"warn\"\n      }\n    }\n  }\n}\n```\n\n## Remediation\n\nSee: <https://supabase.com/docs/guides/database/database-linter?lint=0004_no_primary_key>"] pub NoPrimaryKey { version : "1.0.0" , name : "noPrimaryKey" , severity : pgls_diagnostics :: Severity :: Information , recommended : true , } }
impl SplinterRule for NoPrimaryKey {
    const SQL_FILE_PATH: &'static str = "performance/no_primary_key.sql";
    const DESCRIPTION: &'static str = "Detects if a table does not have a primary key. Tables without a primary key can be inefficient to interact with at scale.";
    const REMEDIATION: &'static str =
        "https://supabase.com/docs/guides/database/database-linter?lint=0004_no_primary_key";
    const REQUIRES_SUPABASE: bool = false;
}
