//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Generated file, do not edit by hand, see `xtask/codegen`"]
use crate::rule::SplinterRule;
::pgls_analyse::declare_rule! { # [doc = "# Unused Index\n\nDetects if an index has never been used and may be a candidate for removal.\n\n## SQL Query\n\n```sql\n(\nselect\n    'unused_index' as \"name!\",\n    'Unused Index' as \"title!\",\n    'INFO' as \"level!\",\n    'EXTERNAL' as \"facing!\",\n    array['PERFORMANCE'] as \"categories!\",\n    'Detects if an index has never been used and may be a candidate for removal.' as \"description!\",\n    format(\n        'Index \\`%s\\` on table \\`%s.%s\\` has not been used',\n        psui.indexrelname,\n        psui.schemaname,\n        psui.relname\n    ) as \"detail!\",\n    'https://supabase.com/docs/guides/database/database-linter?lint=0005_unused_index' as \"remediation!\",\n    jsonb_build_object(\n        'schema', psui.schemaname,\n        'name', psui.relname,\n        'type', 'table'\n    ) as \"metadata!\",\n    format(\n        'unused_index_%s_%s_%s',\n        psui.schemaname,\n        psui.relname,\n        psui.indexrelname\n    ) as \"cache_key!\"\n\nfrom\n    pg_catalog.pg_stat_user_indexes psui\n    join pg_catalog.pg_index pi\n        on psui.indexrelid = pi.indexrelid\n    left join pg_catalog.pg_depend dep\n        on psui.relid = dep.objid\n        and dep.deptype = 'e'\nwhere\n    psui.idx_scan = 0\n    and not pi.indisunique\n    and not pi.indisprimary\n    and dep.objid is null -- exclude tables owned by extensions\n    and psui.schemaname not in (\n        '_timescaledb_cache', '_timescaledb_catalog', '_timescaledb_config', '_timescaledb_internal', 'auth', 'cron', 'extensions', 'graphql', 'graphql_public', 'information_schema', 'net', 'pgmq', 'pgroonga', 'pgsodium', 'pgsodium_masks', 'pgtle', 'pgbouncer', 'pg_catalog', 'pgtle', 'realtime', 'repack', 'storage', 'supabase_functions', 'supabase_migrations', 'tiger', 'topology', 'vault'\n    ))\n```\n\n## Configuration\n\nEnable or disable this rule in your configuration:\n\n```json\n{\n  \"splinter\": {\n    \"rules\": {\n      \"performance\": {\n        \"unusedIndex\": \"warn\"\n      }\n    }\n  }\n}\n```\n\n## Remediation\n\nSee: <https://supabase.com/docs/guides/database/database-linter?lint=0005_unused_index>"] pub UnusedIndex { version : "1.0.0" , name : "unusedIndex" , severity : pgls_diagnostics :: Severity :: Information , recommended : true , } }
impl SplinterRule for UnusedIndex {
    const SQL_FILE_PATH: &'static str = "performance/unused_index.sql";
    const DESCRIPTION: &'static str =
        "Detects if an index has never been used and may be a candidate for removal.";
    const REMEDIATION: &'static str =
        "https://supabase.com/docs/guides/database/database-linter?lint=0005_unused_index";
    const REQUIRES_SUPABASE: bool = false;
}
