[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_lexer_new"
repository.workspace = true
version              = "0.0.0"


[dependencies]
pgt_lexer_new_codegen.workspace = true
pgt_tokenizer.workspace         = true

[dev-dependencies]
insta.workspace = true

[lib]
