[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_statement_splitter"
repository.workspace = true
version              = "0.0.0"


[dependencies]
pgt_diagnostics         = { workspace = true }
pgt_lexer.workspace     = true
pgt_query_ext.workspace = true
pgt_text_size.workspace = true
regex.workspace         = true

[dev-dependencies]
ntest = "0.9.3"
