[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pg_treesitter_queries"
repository.workspace = true
version              = "0.0.0"


[dependencies]
clap                      = { version = "4.5.23", features = ["derive"] }
tree-sitter.workspace     = true
tree_sitter_sql.workspace = true

[dev-dependencies]

[lib]
doctest = false

[features]
