services:
  db:
    # postgres://postgres:postgres@127.0.0.1:5432/postgres
    build: .
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
