[vcs]
enabled = false
client_kind = "git"
use_ignore_file = false

[files]
ignore = []

[db]
host = "127.1.1.1"
port = 5432
username = "postgres"
password = "postgres"
database = "postgres"

# [migrations]
# migrations_dir = "migrations"
# after = 20230912094327

[linter]
enabled = true

[linter.rules]
recommended = true

[linter.rules.safety.banDropColumn]
level = "warn"
options = { test = "HELLO" }


