[vcs]
enabled = false
client_kind = "git"
use_ignore_file = false

[files]
ignore = []

[linter]
enabled = true

[linter.rules]
recommended = true

[db]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "postgres"
database = "postgres"
conn_timeout_secs = 10
