[project]
name = "postgres-language-server"
version = "0.1.0"
description = "A collection of language tools and a Language Server Protocol (LSP) implementation for Postgres, focusing on developer experience and reliable SQL tooling."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mike",
    "zensical>=0.0.30",
]

[tool.uv.sources]
# Zensical's fork of mike, until Zensical has native versioning.
mike = { git = "https://github.com/squidfunk/mike.git" }
