[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pglt_statement_splitter"
repository.workspace = true
version              = "0.0.0"


[dependencies]
pglt_diagnostics         = { workspace = true }
pglt_lexer.workspace     = true
pglt_query_ext.workspace = true
pglt_text_size.workspace = true
regex.workspace          = true

[dev-dependencies]
ntest = "0.9.3"
