[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_treesitter"
repository.workspace = true
version              = "0.0.0"

[lib]
doctest = false

[dependencies]
clap                             = { version = "4.5.23", features = ["derive"] }
pgt_schema_cache.workspace       = true
pgt_text_size.workspace          = true
pgt_treesitter_grammar.workspace = true
tree-sitter.workspace            = true

[dev-dependencies]
pgt_test_utils.workspace = true
