[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pglt_base_db"
repository.workspace = true
version              = "0.0.0"


[dependencies]
line_index.workspace = true
text-size.workspace  = true

pglt_fs.workspace                 = true
pglt_statement_splitter.workspace = true

[dev-dependencies]

[lib]
doctest = false

[features]
