[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pglt_query_ext"
repository.workspace = true
version              = "0.0.0"


[dependencies]
petgraph = "0.6.4"

pg_query.workspace               = true
pglt_diagnostics.workspace       = true
pglt_lexer.workspace             = true
pglt_query_ext_codegen.workspace = true
pglt_text_size.workspace         = true

[lib]
doctest = false
