[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_hover"
repository.workspace = true
version              = "0.0.0"


[dependencies]
humansize                  = { version = "2.1.3" }
pgt_query.workspace        = true
pgt_schema_cache.workspace = true
pgt_text_size.workspace    = true
pgt_treesitter.workspace   = true
schemars                   = { workspace = true, optional = true }
serde                      = { workspace = true, features = ["derive"] }
serde_json                 = { workspace = true }
sqlx.workspace             = true
tokio                      = { version = "1.41.1", features = ["full"] }
tracing                    = { workspace = true }
tree-sitter.workspace      = true
tree_sitter_sql.workspace  = true

[dev-dependencies]
insta                    = { version = "1.42.1" }
pgt_test_utils.workspace = true

[lib]
doctest = false

[features]
schema = ["dep:schemars"]
