[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgls_workspace_macros"
repository.workspace = true
version              = "0.0.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.95" }
quote       = { workspace = true }
syn         = { workspace = true }
