//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Generated file, do not edit by hand, see `xtask/codegen`"]
use crate::rule::SplinterRule;
::pgls_analyse::declare_rule! { # [doc = "# Extension Versions Outdated\n\nDetects extensions that are not using the default (recommended) version.\n\n## SQL Query\n\n```sql\n(\nselect\n    'extension_versions_outdated' as \"name!\",\n    'Extension Versions Outdated' as \"title!\",\n    'WARN' as \"level!\",\n    'EXTERNAL' as \"facing!\",\n    array['SECURITY'] as \"categories!\",\n    'Detects extensions that are not using the default (recommended) version.' as \"description!\",\n    format(\n        'Extension `%s` is using version `%s` but version `%s` is available. Using outdated extension versions may expose the database to security vulnerabilities.',\n        ext.name,\n        ext.installed_version,\n        ext.default_version\n    ) as \"detail!\",\n    'https://supabase.com/docs/guides/database/database-linter?lint=0022_extension_versions_outdated' as \"remediation!\",\n    jsonb_build_object(\n        'extension_name', ext.name,\n        'installed_version', ext.installed_version,\n        'default_version', ext.default_version\n    ) as \"metadata!\",\n    format(\n        'extension_versions_outdated_%s_%s',\n        ext.name,\n        ext.installed_version\n    ) as \"cache_key!\"\nfrom\n    pg_catalog.pg_available_extensions ext\njoin\n    -- ignore versions not in pg_available_extension_versions\n    -- e.g. residue of pg_upgrade\n    pg_catalog.pg_available_extension_versions extv\n    on extv.name = ext.name and extv.installed\nwhere\n    ext.installed_version is not null\n    and ext.default_version is not null\n    and ext.installed_version != ext.default_version\norder by\n    ext.name)\n```\n\n## Configuration\n\nEnable or disable this rule in your configuration:\n\n```json\n{\n  \"splinter\": {\n    \"rules\": {\n      \"security\": {\n        \"extensionVersionsOutdated\": \"warn\"\n      }\n    }\n  }\n}\n```\n\n## Remediation\n\nSee: <https://supabase.com/docs/guides/database/database-linter?lint=0022_extension_versions_outdated>"] pub ExtensionVersionsOutdated { version : "1.0.0" , name : "extensionVersionsOutdated" , severity : pgls_diagnostics :: Severity :: Warning , recommended : true , } }
impl SplinterRule for ExtensionVersionsOutdated {
    const SQL_FILE_PATH: &'static str = "security/extension_versions_outdated.sql";
    const DESCRIPTION: &'static str =
        "Detects extensions that are not using the default (recommended) version.";
    const REMEDIATION: &'static str = "https://supabase.com/docs/guides/database/database-linter?lint=0022_extension_versions_outdated";
    const REQUIRES_SUPABASE: bool = false;
}
