//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Generated file, do not edit by hand, see `xtask/codegen`"]
use crate::rule::SplinterRule;
::pgls_analyse::declare_rule! { # [doc = "/// # Foreign Key to Auth Unique Constraint\n///\n/// Detects user defined foreign keys to unique constraints in the auth schema.\n/// \n/// **Note:** This rule requires Supabase roles (`anon`, `authenticated`, `service_role`). \n/// It will be automatically skipped if these roles don't exist in your database.\n///\n/// ## SQL Query\n///\n/// ```sql\n/// (\n/// select\n///     'fkey_to_auth_unique' as \"name!\",\n///     'Foreign Key to Auth Unique Constraint' as \"title!\",\n///     'ERROR' as \"level!\",\n///     'EXTERNAL' as \"facing!\",\n///     array['SECURITY'] as \"categories!\",\n///     'Detects user defined foreign keys to unique constraints in the auth schema.' as \"description!\",\n///     format(\n///         'Table `%s`.`%s` has a foreign key `%s` referencing an auth unique constraint',\n///         n.nspname, -- referencing schema\n///         c_rel.relname, -- referencing table\n///         c.conname -- fkey name\n///     ) as \"detail!\",\n///     'Drop the foreign key constraint that references the auth schema.' as \"remediation!\",\n///     jsonb_build_object(\n///         'schema', n.nspname,\n///         'name', c_rel.relname,\n///         'foreign_key', c.conname\n///     ) as \"metadata!\",\n///     format(\n///         'fkey_to_auth_unique_%s_%s_%s',\n///         n.nspname, -- referencing schema\n///         c_rel.relname, -- referencing table\n///         c.conname\n///     ) as \"cache_key!\"\n/// from\n///     pg_catalog.pg_constraint c\n///     join pg_catalog.pg_class c_rel\n///         on c.conrelid = c_rel.oid\n///     join pg_catalog.pg_namespace n\n///         on c_rel.relnamespace = n.oid\n///     join pg_catalog.pg_class ref_rel\n///         on c.confrelid = ref_rel.oid\n///     join pg_catalog.pg_namespace cn\n///         on ref_rel.relnamespace = cn.oid\n///     join pg_catalog.pg_index i\n///         on c.conindid = i.indexrelid\n/// where c.contype = 'f'\n///     and cn.nspname = 'auth'\n///     and i.indisunique\n///     and not i.indisprimary)\n/// ```\n///\n/// ## Configuration\n///\n/// Enable or disable this rule in your configuration:\n///\n/// ```json\n/// {\n///   \"splinter\": {\n///     \"rules\": {\n///       \"security\": {\n///         \"fkeyToAuthUnique\": \"warn\"\n///       }\n///     }\n///   }\n/// }\n/// ```\n///\n/// ## Remediation\n///\n/// See: <Drop the foreign key constraint that references the auth schema.>"] pub FkeyToAuthUnique { version : "1.0.0" , name : "fkeyToAuthUnique" , severity : pgls_diagnostics :: Severity :: Error , } }
impl SplinterRule for FkeyToAuthUnique {
    fn sql_file_path() -> &'static str {
        "security/fkey_to_auth_unique.sql"
    }
}
