//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Generated file, do not edit by hand, see `xtask/codegen`"]
use crate::rule::SplinterRule;
::pgls_analyse::declare_rule! { # [doc = "/// # Function Search Path Mutable\n///\n/// Detects functions where the search_path parameter is not set.\n///\n/// ## SQL Query\n///\n/// ```sql\n/// (\n/// select\n///     'function_search_path_mutable' as \"name!\",\n///     'Function Search Path Mutable' as \"title!\",\n///     'WARN' as \"level!\",\n///     'EXTERNAL' as \"facing!\",\n///     array['SECURITY'] as \"categories!\",\n///     'Detects functions where the search_path parameter is not set.' as \"description!\",\n///     format(\n///         'Function \\`%s.%s\\` has a role mutable search_path',\n///         n.nspname,\n///         p.proname\n///     ) as \"detail!\",\n///     'https://supabase.com/docs/guides/database/database-linter?lint=0011_function_search_path_mutable' as \"remediation!\",\n///     jsonb_build_object(\n///         'schema', n.nspname,\n///         'name', p.proname,\n///         'type', 'function'\n///     ) as \"metadata!\",\n///     format(\n///         'function_search_path_mutable_%s_%s_%s',\n///         n.nspname,\n///         p.proname,\n///         md5(p.prosrc) -- required when function is polymorphic\n///     ) as \"cache_key!\"\n/// from\n///     pg_catalog.pg_proc p\n///     join pg_catalog.pg_namespace n\n///         on p.pronamespace = n.oid\n///     left join pg_catalog.pg_depend dep\n///         on p.oid = dep.objid\n///         and dep.deptype = 'e'\n/// where\n///     n.nspname not in (\n///         '_timescaledb_cache', '_timescaledb_catalog', '_timescaledb_config', '_timescaledb_internal', 'auth', 'cron', 'extensions', 'graphql', 'graphql_public', 'information_schema', 'net', 'pgmq', 'pgroonga', 'pgsodium', 'pgsodium_masks', 'pgtle', 'pgbouncer', 'pg_catalog', 'pgtle', 'realtime', 'repack', 'storage', 'supabase_functions', 'supabase_migrations', 'tiger', 'topology', 'vault'\n///     )\n///     and dep.objid is null -- exclude functions owned by extensions\n///     -- Search path not set\n///     and not exists (\n///         select 1\n///         from unnest(coalesce(p.proconfig, '{}')) as config\n///         where config like 'search_path=%'\n///     ))\n/// ```\n///\n/// ## Configuration\n///\n/// Enable or disable this rule in your configuration:\n///\n/// ```json\n/// {\n///   \"splinter\": {\n///     \"rules\": {\n///       \"security\": {\n///         \"functionSearchPathMutable\": \"warn\"\n///       }\n///     }\n///   }\n/// }\n/// ```\n///\n/// ## Remediation\n///\n/// See: <https://supabase.com/docs/guides/database/database-linter?lint=0011_function_search_path_mutable>"] pub FunctionSearchPathMutable { version : "1.0.0" , name : "functionSearchPathMutable" , severity : pgls_diagnostics :: Severity :: Warning , } }
impl SplinterRule for FunctionSearchPathMutable {
    const SQL_FILE_PATH: &'static str = "security/function_search_path_mutable.sql";
    const DESCRIPTION: &'static str =
        "Detects functions where the search_path parameter is not set.";
    const REMEDIATION: &'static str = "https://supabase.com/docs/guides/database/database-linter?lint=0011_function_search_path_mutable";
    const REQUIRES_SUPABASE: bool = false;
}
