//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Generated file, do not edit by hand, see `xtask/codegen`"]
use crate::rule::SplinterRule;
::pgls_analyse::declare_rule! { # [doc = "/// # Insecure Queue Exposed in API\n///\n/// Detects cases where an insecure Queue is exposed over Data APIs\n/// \n/// **Note:** This rule requires Supabase roles (`anon`, `authenticated`, `service_role`). \n/// It will be automatically skipped if these roles don't exist in your database.\n///\n/// ## SQL Query\n///\n/// ```sql\n/// (\n/// select\n///     'insecure_queue_exposed_in_api' as \"name!\",\n///     'Insecure Queue Exposed in API' as \"title!\",\n///     'ERROR' as \"level!\",\n///     'EXTERNAL' as \"facing!\",\n///     array['SECURITY'] as \"categories!\",\n///     'Detects cases where an insecure Queue is exposed over Data APIs' as \"description!\",\n///     format(\n///         'Table \\`%s.%s\\` is public, but RLS has not been enabled.',\n///         n.nspname,\n///         c.relname\n///     ) as \"detail!\",\n///     'https://supabase.com/docs/guides/database/database-linter?lint=0019_insecure_queue_exposed_in_api' as \"remediation!\",\n///     jsonb_build_object(\n///         'schema', n.nspname,\n///         'name', c.relname,\n///         'type', 'table'\n///     ) as \"metadata!\",\n///     format(\n///         'rls_disabled_in_public_%s_%s',\n///         n.nspname,\n///         c.relname\n///     ) as \"cache_key!\"\n/// from\n///     pg_catalog.pg_class c\n///     join pg_catalog.pg_namespace n\n///         on c.relnamespace = n.oid\n/// where\n///     c.relkind in ('r', 'I') -- regular or partitioned tables\n///     and not c.relrowsecurity -- RLS is disabled\n///     and (\n///         pg_catalog.has_table_privilege('anon', c.oid, 'SELECT')\n///         or pg_catalog.has_table_privilege('authenticated', c.oid, 'SELECT')\n///     )\n///     and n.nspname = 'pgmq' -- tables in the pgmq schema\n///     and c.relname like 'q_%' -- only queue tables\n///     -- Constant requirements\n///     and 'pgmq_public' = any(array(select trim(unnest(string_to_array(current_setting('pgrst.db_schemas', 't'), ','))))))\n/// ```\n///\n/// ## Configuration\n///\n/// Enable or disable this rule in your configuration:\n///\n/// ```json\n/// {\n///   \"splinter\": {\n///     \"rules\": {\n///       \"security\": {\n///         \"insecureQueueExposedInApi\": \"warn\"\n///       }\n///     }\n///   }\n/// }\n/// ```\n///\n/// ## Remediation\n///\n/// See: <https://supabase.com/docs/guides/database/database-linter?lint=0019_insecure_queue_exposed_in_api>"] pub InsecureQueueExposedInApi { version : "1.0.0" , name : "insecureQueueExposedInApi" , severity : pgls_diagnostics :: Severity :: Error , } }
impl SplinterRule for InsecureQueueExposedInApi {
    fn sql_file_path() -> &'static str {
        "security/insecure_queue_exposed_in_api.sql"
    }
}
