//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Generated file, do not edit by hand, see `xtask/codegen`"]
use crate::rule::SplinterRule;
::pgls_analyse::declare_rule! { # [doc = "# Materialized View in API\n\nDetects materialized views that are accessible over the Data APIs.\n\n**Note:** This rule requires Supabase roles (`anon`, `authenticated`, `service_role`). It will be automatically skipped if these roles don't exist in your database.\n\n## SQL Query\n\n```sql\n(\nselect\n    'materialized_view_in_api' as \"name!\",\n    'Materialized View in API' as \"title!\",\n    'WARN' as \"level!\",\n    'EXTERNAL' as \"facing!\",\n    array['SECURITY'] as \"categories!\",\n    'Detects materialized views that are accessible over the Data APIs.' as \"description!\",\n    format(\n        'Materialized view \\`%s.%s\\` is selectable by anon or authenticated roles',\n        n.nspname,\n        c.relname\n    ) as \"detail!\",\n    'https://supabase.com/docs/guides/database/database-linter?lint=0016_materialized_view_in_api' as \"remediation!\",\n    jsonb_build_object(\n        'schema', n.nspname,\n        'name', c.relname,\n        'type', 'materialized view'\n    ) as \"metadata!\",\n    format(\n        'materialized_view_in_api_%s_%s',\n        n.nspname,\n        c.relname\n    ) as \"cache_key!\"\nfrom\n    pg_catalog.pg_class c\n    join pg_catalog.pg_namespace n\n        on n.oid = c.relnamespace\n    left join pg_catalog.pg_depend dep\n        on c.oid = dep.objid\n        and dep.deptype = 'e'\nwhere\n    c.relkind = 'm'\n    and (\n        pg_catalog.has_table_privilege('anon', c.oid, 'SELECT')\n        or pg_catalog.has_table_privilege('authenticated', c.oid, 'SELECT')\n    )\n    and n.nspname = any(array(select trim(unnest(string_to_array(current_setting('pgrst.db_schemas', 't'), ',')))))\n    and n.nspname not in (\n        '_timescaledb_cache', '_timescaledb_catalog', '_timescaledb_config', '_timescaledb_internal', 'auth', 'cron', 'extensions', 'graphql', 'graphql_public', 'information_schema', 'net', 'pgmq', 'pgroonga', 'pgsodium', 'pgsodium_masks', 'pgtle', 'pgbouncer', 'pg_catalog', 'pgtle', 'realtime', 'repack', 'storage', 'supabase_functions', 'supabase_migrations', 'tiger', 'topology', 'vault'\n    )\n    and dep.objid is null)\n```\n\n## Configuration\n\nEnable or disable this rule in your configuration:\n\n```json\n{\n  \"splinter\": {\n    \"rules\": {\n      \"security\": {\n        \"materializedViewInApi\": \"warn\"\n      }\n    }\n  }\n}\n```\n\n## Remediation\n\nSee: <https://supabase.com/docs/guides/database/database-linter?lint=0016_materialized_view_in_api>"] pub MaterializedViewInApi { version : "1.0.0" , name : "materializedViewInApi" , severity : pgls_diagnostics :: Severity :: Warning , recommended : true , } }
impl SplinterRule for MaterializedViewInApi {
    const SQL_FILE_PATH: &'static str = "security/materialized_view_in_api.sql";
    const DESCRIPTION: &'static str =
        "Detects materialized views that are accessible over the Data APIs.";
    const REMEDIATION: &'static str = "https://supabase.com/docs/guides/database/database-linter?lint=0016_materialized_view_in_api";
    const REQUIRES_SUPABASE: bool = true;
}
