//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Generated file, do not edit by hand, see `xtask/codegen`"]
use crate::rule::SplinterRule;
::pgls_analyse::declare_rule! { # [doc = "/// # Policy Exists RLS Disabled\n///\n/// Detects cases where row level security (RLS) policies have been created, but RLS has not been enabled for the underlying table.\n///\n/// ## SQL Query\n///\n/// ```sql\n/// (\n/// select\n///     'policy_exists_rls_disabled' as \"name!\",\n///     'Policy Exists RLS Disabled' as \"title!\",\n///     'ERROR' as \"level!\",\n///     'EXTERNAL' as \"facing!\",\n///     array['SECURITY'] as \"categories!\",\n///     'Detects cases where row level security (RLS) policies have been created, but RLS has not been enabled for the underlying table.' as \"description!\",\n///     format(\n///         'Table \\`%s.%s\\` has RLS policies but RLS is not enabled on the table. Policies include %s.',\n///         n.nspname,\n///         c.relname,\n///         array_agg(p.polname order by p.polname)\n///     ) as \"detail!\",\n///     'https://supabase.com/docs/guides/database/database-linter?lint=0007_policy_exists_rls_disabled' as \"remediation!\",\n///     jsonb_build_object(\n///         'schema', n.nspname,\n///         'name', c.relname,\n///         'type', 'table'\n///     ) as \"metadata!\",\n///     format(\n///         'policy_exists_rls_disabled_%s_%s',\n///         n.nspname,\n///         c.relname\n///     ) as \"cache_key!\"\n/// from\n///     pg_catalog.pg_policy p\n///     join pg_catalog.pg_class c\n///         on p.polrelid = c.oid\n///     join pg_catalog.pg_namespace n\n///         on c.relnamespace = n.oid\n///     left join pg_catalog.pg_depend dep\n///         on c.oid = dep.objid\n///         and dep.deptype = 'e'\n/// where\n///     c.relkind = 'r' -- regular tables\n///     and n.nspname not in (\n///         '_timescaledb_cache', '_timescaledb_catalog', '_timescaledb_config', '_timescaledb_internal', 'auth', 'cron', 'extensions', 'graphql', 'graphql_public', 'information_schema', 'net', 'pgmq', 'pgroonga', 'pgsodium', 'pgsodium_masks', 'pgtle', 'pgbouncer', 'pg_catalog', 'pgtle', 'realtime', 'repack', 'storage', 'supabase_functions', 'supabase_migrations', 'tiger', 'topology', 'vault'\n///     )\n///     -- RLS is disabled\n///     and not c.relrowsecurity\n///     and dep.objid is null -- exclude tables owned by extensions\n/// group by\n///     n.nspname,\n///     c.relname)\n/// ```\n///\n/// ## Configuration\n///\n/// Enable or disable this rule in your configuration:\n///\n/// ```json\n/// {\n///   \"splinter\": {\n///     \"rules\": {\n///       \"security\": {\n///         \"policyExistsRlsDisabled\": \"warn\"\n///       }\n///     }\n///   }\n/// }\n/// ```\n///\n/// ## Remediation\n///\n/// See: <https://supabase.com/docs/guides/database/database-linter?lint=0007_policy_exists_rls_disabled>"] pub PolicyExistsRlsDisabled { version : "1.0.0" , name : "policyExistsRlsDisabled" , severity : pgls_diagnostics :: Severity :: Error , } }
impl SplinterRule for PolicyExistsRlsDisabled {
    const SQL_FILE_PATH: &'static str = "security/policy_exists_rls_disabled.sql";
    const DESCRIPTION: &'static str = "Detects cases where row level security (RLS) policies have been created, but RLS has not been enabled for the underlying table.";
    const REMEDIATION: &'static str = "https://supabase.com/docs/guides/database/database-linter?lint=0007_policy_exists_rls_disabled";
    const REQUIRES_SUPABASE: bool = false;
}
