//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Generated file, do not edit by hand, see `xtask/codegen`"]
use crate::rule::SplinterRule;
::pgls_analyse::declare_rule! { # [doc = "# RLS Disabled in Public\n\nDetects cases where row level security (RLS) has not been enabled on tables in schemas exposed to PostgREST\n\n**Note:** This rule requires Supabase roles (`anon`, `authenticated`, `service_role`). It will be automatically skipped if these roles don't exist in your database.\n\n## SQL Query\n\n```sql\n(\nselect\n    'rls_disabled_in_public' as \"name!\",\n    'RLS Disabled in Public' as \"title!\",\n    'ERROR' as \"level!\",\n    'EXTERNAL' as \"facing!\",\n    array['SECURITY'] as \"categories!\",\n    'Detects cases where row level security (RLS) has not been enabled on tables in schemas exposed to PostgREST' as \"description!\",\n    format(\n        'Table \\`%s.%s\\` is public, but RLS has not been enabled.',\n        n.nspname,\n        c.relname\n    ) as \"detail!\",\n    'https://supabase.com/docs/guides/database/database-linter?lint=0013_rls_disabled_in_public' as \"remediation!\",\n    jsonb_build_object(\n        'schema', n.nspname,\n        'name', c.relname,\n        'type', 'table'\n    ) as \"metadata!\",\n    format(\n        'rls_disabled_in_public_%s_%s',\n        n.nspname,\n        c.relname\n    ) as \"cache_key!\"\nfrom\n    pg_catalog.pg_class c\n    join pg_catalog.pg_namespace n\n        on c.relnamespace = n.oid\nwhere\n    c.relkind = 'r' -- regular tables\n    -- RLS is disabled\n    and not c.relrowsecurity\n    and (\n        pg_catalog.has_table_privilege('anon', c.oid, 'SELECT')\n        or pg_catalog.has_table_privilege('authenticated', c.oid, 'SELECT')\n    )\n    and n.nspname = any(array(select trim(unnest(string_to_array(current_setting('pgrst.db_schemas', 't'), ',')))))\n    and n.nspname not in (\n        '_timescaledb_cache', '_timescaledb_catalog', '_timescaledb_config', '_timescaledb_internal', 'auth', 'cron', 'extensions', 'graphql', 'graphql_public', 'information_schema', 'net', 'pgmq', 'pgroonga', 'pgsodium', 'pgsodium_masks', 'pgtle', 'pgbouncer', 'pg_catalog', 'pgtle', 'realtime', 'repack', 'storage', 'supabase_functions', 'supabase_migrations', 'tiger', 'topology', 'vault'\n    ))\n```\n\n## Configuration\n\nEnable or disable this rule in your configuration:\n\n```json\n{\n  \"splinter\": {\n    \"rules\": {\n      \"security\": {\n        \"rlsDisabledInPublic\": \"warn\"\n      }\n    }\n  }\n}\n```\n\n## Remediation\n\nSee: <https://supabase.com/docs/guides/database/database-linter?lint=0013_rls_disabled_in_public>"] pub RlsDisabledInPublic { version : "1.0.0" , name : "rlsDisabledInPublic" , severity : pgls_diagnostics :: Severity :: Error , recommended : true , } }
impl SplinterRule for RlsDisabledInPublic {
    const SQL_FILE_PATH: &'static str = "security/rls_disabled_in_public.sql";
    const DESCRIPTION: &'static str = "Detects cases where row level security (RLS) has not been enabled on tables in schemas exposed to PostgREST";
    const REMEDIATION: &'static str = "https://supabase.com/docs/guides/database/database-linter?lint=0013_rls_disabled_in_public";
    const REQUIRES_SUPABASE: bool = true;
}
