//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Generated file, do not edit by hand, see `xtask/codegen`"]
use crate::rule::SplinterRule;
::pgls_analyse::declare_rule! { # [doc = "# RLS Enabled No Policy\n\nDetects cases where row level security (RLS) has been enabled on a table but no RLS policies have been created.\n\n## SQL Query\n\n```sql\n(\nselect\n    'rls_enabled_no_policy' as \"name!\",\n    'RLS Enabled No Policy' as \"title!\",\n    'INFO' as \"level!\",\n    'EXTERNAL' as \"facing!\",\n    array['SECURITY'] as \"categories!\",\n    'Detects cases where row level security (RLS) has been enabled on a table but no RLS policies have been created.' as \"description!\",\n    format(\n        'Table \\`%s.%s\\` has RLS enabled, but no policies exist',\n        n.nspname,\n        c.relname\n    ) as \"detail!\",\n    'https://supabase.com/docs/guides/database/database-linter?lint=0008_rls_enabled_no_policy' as \"remediation!\",\n    jsonb_build_object(\n        'schema', n.nspname,\n        'name', c.relname,\n        'type', 'table'\n    ) as \"metadata!\",\n    format(\n        'rls_enabled_no_policy_%s_%s',\n        n.nspname,\n        c.relname\n    ) as \"cache_key!\"\nfrom\n    pg_catalog.pg_class c\n    left join pg_catalog.pg_policy p\n        on p.polrelid = c.oid\n    join pg_catalog.pg_namespace n\n        on c.relnamespace = n.oid\n    left join pg_catalog.pg_depend dep\n        on c.oid = dep.objid\n        and dep.deptype = 'e'\nwhere\n    c.relkind = 'r' -- regular tables\n    and n.nspname not in (\n        '_timescaledb_cache', '_timescaledb_catalog', '_timescaledb_config', '_timescaledb_internal', 'auth', 'cron', 'extensions', 'graphql', 'graphql_public', 'information_schema', 'net', 'pgmq', 'pgroonga', 'pgsodium', 'pgsodium_masks', 'pgtle', 'pgbouncer', 'pg_catalog', 'pgtle', 'realtime', 'repack', 'storage', 'supabase_functions', 'supabase_migrations', 'tiger', 'topology', 'vault'\n    )\n    -- RLS is enabled\n    and c.relrowsecurity\n    and p.polname is null\n    and dep.objid is null -- exclude tables owned by extensions\ngroup by\n    n.nspname,\n    c.relname)\n```\n\n## Configuration\n\nEnable or disable this rule in your configuration:\n\n```json\n{\n  \"splinter\": {\n    \"rules\": {\n      \"security\": {\n        \"rlsEnabledNoPolicy\": \"warn\"\n      }\n    }\n  }\n}\n```\n\n## Remediation\n\nSee: <https://supabase.com/docs/guides/database/database-linter?lint=0008_rls_enabled_no_policy>"] pub RlsEnabledNoPolicy { version : "1.0.0" , name : "rlsEnabledNoPolicy" , severity : pgls_diagnostics :: Severity :: Information , recommended : true , } }
impl SplinterRule for RlsEnabledNoPolicy {
    const SQL_FILE_PATH: &'static str = "security/rls_enabled_no_policy.sql";
    const DESCRIPTION: &'static str = "Detects cases where row level security (RLS) has been enabled on a table but no RLS policies have been created.";
    const REMEDIATION: &'static str =
        "https://supabase.com/docs/guides/database/database-linter?lint=0008_rls_enabled_no_policy";
    const REQUIRES_SUPABASE: bool = false;
}
