//! Generated file, do not edit by hand, see `xtask/codegen`

#![doc = r" Generated file, do not edit by hand, see `xtask/codegen`"]
use crate::rule::SplinterRule;
::pgls_analyse::declare_rule! { # [doc = "/// # Unsupported reg types\n///\n/// Identifies columns using unsupported reg* types outside pg_catalog schema, which prevents database upgrades using pg_upgrade.\n///\n/// ## SQL Query\n///\n/// ```sql\n/// (\n/// select\n///     'unsupported_reg_types' as \"name!\",\n///     'Unsupported reg types' as \"title!\",\n///     'WARN' as \"level!\",\n///     'EXTERNAL' as \"facing!\",\n///     array['SECURITY'] as \"categories!\",\n///     'Identifies columns using unsupported reg* types outside pg_catalog schema, which prevents database upgrades using pg_upgrade.' as \"description!\",\n///     format(\n///         'Table \\`%s.%s\\` has a column \\`%s\\` with unsupported reg* type \\`%s\\`.',\n///         n.nspname,\n///         c.relname,\n///         a.attname,\n///         t.typname\n///     ) as \"detail!\",\n///     'https://supabase.com/docs/guides/database/database-linter?lint=unsupported_reg_types' as \"remediation!\",\n///     jsonb_build_object(\n///         'schema', n.nspname,\n///         'name', c.relname,\n///         'column', a.attname,\n///         'type', 'table'\n///     ) as \"metadata!\",\n///     format(\n///         'unsupported_reg_types_%s_%s_%s',\n///         n.nspname,\n///         c.relname,\n///         a.attname\n///     ) AS cache_key\n/// from\n///     pg_catalog.pg_attribute a\n///     join pg_catalog.pg_class c\n///         on a.attrelid = c.oid\n///     join pg_catalog.pg_namespace n\n///         on c.relnamespace = n.oid\n///     join pg_catalog.pg_type t\n///         on a.atttypid = t.oid\n///     join pg_catalog.pg_namespace tn\n///         on t.typnamespace = tn.oid\n/// where\n///     tn.nspname = 'pg_catalog'\n///     and t.typname in ('regcollation', 'regconfig', 'regdictionary', 'regnamespace', 'regoper', 'regoperator', 'regproc', 'regprocedure')\n///     and n.nspname not in ('pg_catalog', 'information_schema', 'pgsodium'))\n/// ```\n///\n/// ## Configuration\n///\n/// Enable or disable this rule in your configuration:\n///\n/// ```json\n/// {\n///   \"splinter\": {\n///     \"rules\": {\n///       \"security\": {\n///         \"unsupportedRegTypes\": \"warn\"\n///       }\n///     }\n///   }\n/// }\n/// ```\n///\n/// ## Remediation\n///\n/// See: <https://supabase.com/docs/guides/database/database-linter?lint=unsupported_reg_types>"] pub UnsupportedRegTypes { version : "1.0.0" , name : "unsupportedRegTypes" , severity : pgls_diagnostics :: Severity :: Warning , } }
impl SplinterRule for UnsupportedRegTypes {
    fn sql_file_path() -> &'static str {
        "security/unsupported_reg_types.sql"
    }
}
