[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pglt_typecheck"
repository.workspace = true
version              = "0.0.0"


[dependencies]
pglt_console.workspace      = true
pglt_diagnostics.workspace  = true
pglt_query_ext.workspace    = true
pglt_schema_cache.workspace = true
pglt_text_size.workspace    = true
sqlx.workspace              = true
tokio.workspace             = true
tree-sitter.workspace       = true
tree_sitter_sql.workspace   = true

[dev-dependencies]
insta.workspace           = true
pglt_test_utils.workspace = true

[lib]
doctest = false

[features]
