[package]
description = "Internal script to make sure that the metadata or the rules are correct"
edition     = "2021"
name        = "rules_check"
publish     = false
version     = "0.0.0"

[dependencies]
anyhow                  = { workspace = true }
pglt_analyse            = { workspace = true }
pglt_analyser           = { workspace = true }
pglt_console            = { workspace = true }
pglt_diagnostics        = { workspace = true }
pglt_query_ext          = { workspace = true }
pglt_statement_splitter = { workspace = true }
pglt_workspace          = { workspace = true }
pulldown-cmark          = "0.12.2"
