[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_parser"
repository.workspace = true
version              = "0.0.0"


[dependencies]
pgt_lexer_new.workspace      = true
pgt_parser_codegen.workspace = true

[dev-dependencies]
insta.workspace = true

[lib]
