//! Generated file, do not edit by hand, see `xtask/codegen`

use crate::linter_registry::RegistryLinterRule;
use pgls_analyse::{RegistryVisitor, RuleKey};
pub fn visit_registry<V: RegistryVisitor>(registry: &mut V) {
    registry.record_category::<crate::lint::Lint>();
}
#[doc = r" Maps rule keys to factory functions that create rule executors"]
#[doc = r" This function is generated by codegen and includes all linter rules"]
pub fn get_linter_rule_factory(key: &RuleKey) -> Option<Box<dyn FnOnce() -> RegistryLinterRule>> {
    match key.rule_name() {
        "addSerialColumn" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::add_serial_column::AddSerialColumn,
            >()
        })),
        "addingFieldWithDefault" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::adding_field_with_default::AddingFieldWithDefault,
            >()
        })),
        "addingForeignKeyConstraint" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::adding_foreign_key_constraint::AddingForeignKeyConstraint,
            >()
        })),
        "addingNotNullField" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::adding_not_null_field::AddingNotNullField,
            >()
        })),
        "addingPrimaryKeyConstraint" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::adding_primary_key_constraint::AddingPrimaryKeyConstraint,
            >()
        })),
        "addingRequiredField" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::adding_required_field::AddingRequiredField,
            >()
        })),
        "banCharField" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::ban_char_field::BanCharField,
            >()
        })),
        "banConcurrentIndexCreationInTransaction" => Some(Box::new(|| {
            crate :: linter_registry :: RegistryLinterRule :: new :: < crate::lint::safety::ban_concurrent_index_creation_in_transaction :: BanConcurrentIndexCreationInTransaction > ()
        })),
        "banDropColumn" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::ban_drop_column::BanDropColumn,
            >()
        })),
        "banDropDatabase" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::ban_drop_database::BanDropDatabase,
            >()
        })),
        "banDropNotNull" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::ban_drop_not_null::BanDropNotNull,
            >()
        })),
        "banDropTable" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::ban_drop_table::BanDropTable,
            >()
        })),
        "banTruncateCascade" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::ban_truncate_cascade::BanTruncateCascade,
            >()
        })),
        "changingColumnType" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::changing_column_type::ChangingColumnType,
            >()
        })),
        "constraintMissingNotValid" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::constraint_missing_not_valid::ConstraintMissingNotValid,
            >()
        })),
        "creatingEnum" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::creating_enum::CreatingEnum,
            >()
        })),
        "disallowUniqueConstraint" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::disallow_unique_constraint::DisallowUniqueConstraint,
            >()
        })),
        "lockTimeoutWarning" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::lock_timeout_warning::LockTimeoutWarning,
            >()
        })),
        "multipleAlterTable" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::multiple_alter_table::MultipleAlterTable,
            >()
        })),
        "preferBigInt" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::prefer_big_int::PreferBigInt,
            >()
        })),
        "preferBigintOverInt" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::prefer_bigint_over_int::PreferBigintOverInt,
            >()
        })),
        "preferBigintOverSmallint" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::prefer_bigint_over_smallint::PreferBigintOverSmallint,
            >()
        })),
        "preferIdentity" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::prefer_identity::PreferIdentity,
            >()
        })),
        "preferJsonb" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::prefer_jsonb::PreferJsonb,
            >()
        })),
        "preferRobustStmts" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::prefer_robust_stmts::PreferRobustStmts,
            >()
        })),
        "preferTextField" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::prefer_text_field::PreferTextField,
            >()
        })),
        "preferTimestamptz" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::prefer_timestamptz::PreferTimestamptz,
            >()
        })),
        "renamingColumn" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::renaming_column::RenamingColumn,
            >()
        })),
        "renamingTable" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::renaming_table::RenamingTable,
            >()
        })),
        "requireConcurrentIndexCreation" => Some(Box::new(|| {
            crate :: linter_registry :: RegistryLinterRule :: new :: < crate::lint::safety::require_concurrent_index_creation :: RequireConcurrentIndexCreation > ()
        })),
        "requireConcurrentIndexDeletion" => Some(Box::new(|| {
            crate :: linter_registry :: RegistryLinterRule :: new :: < crate::lint::safety::require_concurrent_index_deletion :: RequireConcurrentIndexDeletion > ()
        })),
        "runningStatementWhileHoldingAccessExclusive" => Some(Box::new(|| {
            crate :: linter_registry :: RegistryLinterRule :: new :: < crate::lint::safety::running_statement_while_holding_access_exclusive :: RunningStatementWhileHoldingAccessExclusive > ()
        })),
        "transactionNesting" => Some(Box::new(|| {
            crate::linter_registry::RegistryLinterRule::new::<
                crate::lint::safety::transaction_nesting::TransactionNesting,
            >()
        })),
        _ => None,
    }
}
