[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pglt_flags"
repository.workspace = true
version              = "0.0.0"


[dependencies]
pglt_console = { workspace = true }

[dev-dependencies]

[features]
