
[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_suppressions"
repository.workspace = true
version              = "0.0.0"

[dependencies]
pgt_analyse     = { workspace = true }
pgt_diagnostics = { workspace = true }
pgt_text_size   = { workspace = true }
tracing         = { workspace = true }
