[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pglt_configuration"
repository.workspace = true
version              = "0.0.0"


[dependencies]
biome_deserialize        = { workspace = true, features = ["schema"] }
biome_deserialize_macros = { workspace = true }
bpaf                     = { workspace = true }
indexmap                 = { workspace = true }
pglt_analyse             = { workspace = true }
pglt_analyser            = { workspace = true }
pglt_console             = { workspace = true }
pglt_diagnostics         = { workspace = true }
pglt_text_size           = { workspace = true }
rustc-hash               = { workspace = true }
schemars                 = { workspace = true, features = ["indexmap1"], optional = true }
serde                    = { workspace = true, features = ["derive"] }
serde_json               = { workspace = true, features = ["raw_value"] }
toml                     = { workspace = true }

[lib]
doctest = false

[features]
schema = ["dep:schemars", "schemars/indexmap"]
