[package]
description = "Download PostgreSQL regression tests"
edition     = "2021"
name        = "download_regression_tests"
publish     = false
version     = "0.0.0"

[dependencies]
anyhow                 = { workspace = true }
camino.workspace       = true
pgt_query              = { workspace = true }
pgt_statement_splitter = { workspace = true }
regex.workspace        = true
serde.workspace        = true
serde_json.workspace   = true
