[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_plpgsql_check"
repository.workspace = true
version              = "0.0.0"


[dependencies]
pgt_console      = { workspace = true }
pgt_diagnostics  = { workspace = true }
pgt_query        = { workspace = true }
pgt_query_ext    = { workspace = true }
pgt_schema_cache = { workspace = true }
pgt_text_size    = { workspace = true }
regex            = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
sqlx             = { workspace = true }
tree-sitter      = { workspace = true }

[dev-dependencies]
pgt_test_utils = { workspace = true }

[lib]
