[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pglt_query_proto_parser"
repository.workspace = true
version              = "0.0.0"


[dependencies]
convert_case   = "0.6.0"
protobuf       = "3.3.0"
protobuf-parse = "3.3.0"

[lib]
doctest = false
