name: Publish to NPM & Brew

on:
  workflow_call:
    inputs:
      release-tag:
        type: string
        required: true
      is-prerelease:
        type: string
        required: true

jobs:
  publish:
    name: Publish All the Things
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"

      - name: Generate Packages
        id: generate-packages
        run: node packages/@postgrestools/postgrestools/scripts/generate-packages.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ inputs.release-tag }}
          PRERELEASE: ${{ inputs.is-prerelease }}

      - name: Publish npm packages as nightly
        if: inputs.is-prerelease == 'true'
        run: |
          for package in packages/@postgrestools/*; do
            npm publish "$package" --tag nightly --access public --provenance
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} #

      - name: Publish npm packages as latest
        if: inputs.is-prerelease != 'true'
        run: |
          for package in packages/@postgrestools/*; do
            version="${{ inputs.release-tag }}"

            if npm view "$package@$version" version 2>/dev/null; then
              echo "Package $package@$version already exists, skipping..."
            else
              echo "Publishing $package@$version..."
              npm publish "$package" --tag latest --access public --provenance
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
