name: Publish to NPM & Brew

on:
  workflow_call:
    inputs:
      release-tag:
        type: string
        required: true
      is-prerelease:
        type: string
        required: true

jobs:
  publish:
    name: Publish All the Things
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"

      - name: Verify `jq` is installed
        run: |
          if ! jq --version 2>/dev/null; then
            echo "jq not installed, required for extracting package names."
            exit 1
          else

      - name: Generate Packages
        id: generate-packages
        run: node packages/@postgrestools/postgrestools/scripts/generate-packages.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ inputs.release-tag }}
          PRERELEASE: ${{ inputs.is-prerelease }}

      - name: Publish npm packages as nightly
        if: inputs.is-prerelease == 'true'
        run: |
          for package in packages/@postgrestools/*; do
            npm publish "$package" --tag nightly --access public --provenance
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} #

      - name: Publish npm packages as latest
        if: inputs.is-prerelease != 'true'
        run: |
          for package in packages/@postgrestools/*; do
<<<<<<< HEAD
            package_basename=$(basename "$package")
            package_name="@postgrestools/$package_basename"
            package_version="${{ inputs.release-tag }}"

            if npm view "$package_name@$package_version" version 2>/dev/null; then
              echo "Package $package_name@$package_version already exists, skipping..."
            else
              echo "Publishing $package_name@$package_version..."
=======
            version="${{ inputs.release-tag }}"
            npm_package_name=$(cat "$package/package.json" | jq ".name")

            if npm view "$npm_package_name@$version" version 2>/dev/null; then
              echo "Package $npm_package_name@$version already exists, skipping..."
            else
              echo "Publishing $npm_package_name@$version..."
>>>>>>> ced56b59 (ok)
              npm publish "$package" --tag latest --access public --provenance
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
